name: manage-azure-policy-062142e0
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Keys_should_have_the_specified_maximum_validity_period_49a22571-d204-4c91-a7b6-09b1a586fbc9/**'
#      - .github/workflows/manage-azure-policy-062142e0.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_062142e0}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Keys_should_have_the_specified_maximum_validity_period_49a22571-d204-4c91-a7b6-09b1a586fbc9/**
